---
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.5.0

workflows:
  circleci-agent-publish-orb-pipeline:

    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: feedyard/circleci-agent-publish
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          context: ci
          name: trigger-integration-dev
          ssh-fingerprints: $CI_FINGERPRINT
          cleanup-tags: true
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: $CI_FINGERPRINT
          cleanup-tags: true
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master