---
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.5.0
  circle-compare-url: iynere/compare-url@0.4.10

workflows:
  circleci-agent-publish-orb-pipeline:

    jobs:
      - circle-compare-url/reconstruct:
          context: ci
          circle-token: CIRCLE_TOKEN
      - post-message
      - calc


executors:

  circleci-base-agent:
    description: The docker container to use when running circleci-agent-publish jobs
    docker:
      - image: quay.io/feedyard/circleci-base-agent

jobs:

  post-message:
    description: just echo a message
    executor: circleci-base-agent
    steps:
      - run:
          name: the echo
          command: echo 'simple post message test'

  calc:
    description: do the commit calculation
    executor: circleci-base-agent
    steps:
      - run:
          name: construct/push git integration tag
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            # only publish a major release if there are new jobs or commands
            if [[ $(git diff $COMMIT_RANGE --name-status | \
              grep -e "A      src/commands" -e "A      src/jobs") ]]; then
              INTEGRATION_TAG=tag-major-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}

            # publish a minor release if there are other changes to jobs or commands
            elif [[ $(git diff $COMMIT_RANGE --name-status | \
              grep -e "src/commands" -e "src/jobs") ]]; then
              INTEGRATION_TAG=tag-minor-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}

            # patch release if any changers to examples, executors, @orb.yml
            elif [[ $(git diff $COMMIT_RANGE --name-status | \
              grep -e "src/examples" -e "src/executors" -e "src/@orb.yml") ]]; then
              INTEGRATION_TAG=tag-patch-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}

            # otherwise, don't publish a release
            else
              INTEGRATION_TAG=tag-skip-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            fi

            echo $INTEGRATION_TAG


#      - orb-tools/lint
#
#      - orb-tools/pack:
#          requires:
#            - orb-tools/lint
#
#      - orb-tools/publish-dev:
#          orb-name: feedyard/circleci-agent-publish
#          requires:
#            - orb-tools/pack
#
#      - orb-tools/trigger-integration-workflow:
#          context: ci
#          name: trigger-integration-dev
#          ssh-fingerprints: $CI_FINGERPRINT
#          cleanup-tags: true
#          requires:
#            - orb-tools/publish-dev
#          filters:
#            branches:
#              only: master
#
#      - orb-tools/trigger-integration-workflow:
#          name: trigger-integration-master
#          ssh-fingerprints: $CI_FINGERPRINT
#          cleanup-tags: true
#          tag: master
#          requires:
#            - orb-tools/publish-dev
#          filters:
#            branches:
#              only: master
