# src/commands/build.yaml

description: Build executor Docker image.

parameters:

  dockerfile:
    description: Name of dockerfile
    type: string
    default: Dockerfile

  path:
    description: Path to the directory containing your Dockerfile and build context
    type: string
    default: .

  image:
    description: Name of image
    type: string

  tag:
    description: Value for tag
    type: string
    default: dev.${CIRCLE_SHA1:0:7}

  registry:
    description: Name of registry
    type: string
    default: docker.io

  extra-build-args:
    description: >
      Extra flags to pass to docker build. For examples, see
      https://docs.docker.com/engine/reference/commandline/build
    type: string
    default: ""

steps:
  - run:
      name: Build executor Docker image
      command: |
        docker build \
          <<#parameters.extra-build-args>><<parameters.extra-build-args>><</parameters.extra-build-args>> \
          -f << parameters.dockerfile >> -t \
          << parameters.registry >>/<< parameters.image >>:<< parameters.tag >> \
          << parameters.path >>
